website_controllers:
    resource: ../src/Http/Controller/Website
    type: annotation
    name_prefix: app_website_
    prefix:
        fr: ''
        en: '/en'

controllers:
    resource: ../src/Http/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute
